version: '3'
services:
    odoonginx:
        container_name: odoo
        image: odoo:latest
        volumes:
            - ./addons-extra:/mnt/extra-addons
            - ./etc/odoo/config:/etc/odoo
            - odoo-web-data:/var/lib/odoo
        ports:
            - "8069:8069"
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
          - 80:80
          - 443:443
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
volumes:
    odoo-web-data:


version: '2'
services:
  db_nginx:
    image: postgres:13
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    ports:
      - "5432:5432"
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo_nginx:
    image: thtom/odoo:v14.0
    user: root
    depends_on:
      - db_nginx
    ports:
      - "10014:8069"
      - "20014:8072" # live chat
    tty: true
    command: --
#    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service

  nginx_odoo:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d