version: '2'
services:
  db_nginx:
    image: postgres:13
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    ports:
      - "5432:5432"
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo_nginx:
    image: thtom/odoo:v14.0
    user: root
    depends_on:
      - db_nginx
    ports:
      - "10018:8069"
      - "20018:8072" # live chat
    tty: true
    command: --
#    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST=db_nginx
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service

  nginx_odoo:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d